# Generated by Django 3.0.6 on 2020-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='direction',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
